name: CI/CD Dashboard Oukale

env:
  "S3_BUCKET_NAME": "s3dashboardoukale"
  "EBS_APPLICATION_NAME": "dashboard-oukale-beanstalk"
  "EBS_ENVIRONMENT_NAME": "Dashboard-oukale-beanstalk-env"
  "AWS_REGION": "us-east-1"
  "DEPLOY_PACKAGE_NAME": "dashboard-oukale-${{github.sha}}.zip"
  
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone le code github
        uses: actions/checkout@v3

      - name: Zip le code github
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # node-version: 16
          aws-access-key-id: ${{secrets.ACCESS_KEY_ID_LAGAMA}}
          aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY_LAGAMA}}
          aws-region: ${{env.AWS_REGION}}
          
      - name: Télécharger le déploiement vers le bucket S3 
        run: aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}} s3://${{env.S3_BUCKET_NAME}}/
      
      - name: Créer une nouvelle version de l'application Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{env.EBS_APPLICATION_NAME}} \
          --source-bundle S3Bucket="${{env.S3_BUCKET_NAME}}",S3Key="${{env.DEPLOY_PACKAGE_NAME}}" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
        
      - name: Déployer une nouvelle version de l'application ElasticBeanstalk
        run: aws elasticbeanstalk update-environment --environment-name ${{env.EBS_ENVIRONMENT_NAME}} --version-label "ver-${{ github.sha }}"
      
      - name: Imprimer un message de réussite à l'issue de l'opération
        run: echo "CI/CD pipeline exécuté avec succès"
